services:
  postgres:
    image: postgres:14.6
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data 
      - ./db:/docker-entrypoint-initdb.d
  # Frontend service
  fronted: 
    image: frontend:1.0.0-alpine
    ports:
      - 4173:80
    env_file:
      - .env
  # Backend service
  backend: 
    image: backend:1.0.0 
    ports:
      - 8001:8001
    env_file:
      - .env
     
  #Database service 
volumes:
  pgdata:
