namespace: app1
resources:
  - database.yaml
  - backend.yaml
  - frontend.yaml
  - namespace.yaml

configMapGenerator:
- name: pg-configmap
  files: 
  - inital_db.sql

secretGenerator:
- name: pg-secrets-ag
  envs:
  - .env
